FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["SipayTestCase.Web/SipayTestCase.Web.csproj", "SipayTestCase.Web/"]
RUN dotnet restore "SipayTestCase.Web/SipayTestCase.Web.csproj"
COPY . .
WORKDIR "/src/SipayTestCase.Web"
RUN dotnet build "SipayTestCase.Web.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "SipayTestCase.Web.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "SipayTestCase.Web.dll"]
